databases:
  - name: communityhubdb
    plan: free
    databaseName: communityhub
    user: communityhub

services:
  - type: web
    plan: free
    name: community-hub
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn community_hub.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: communityhubdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
